### ISSUE TITLE
Support TAQL WHERE clause

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/xarray-ms#10]
To allow selection on fields, data descriptor id's etc.

**Comment by o-smirnov** [comment]
This should be a one-liner -- just call ``query()`` on the table object, and you get another table object back, or am I missing some subtlety?

**Comment by sjperkins** [comment]
It does look like this could be a one-liner, see [here](https://github.com/ska-sa/xarray-ms/blob/3b9aef5576f8c26f1585d02124c61ef2547b40bb/xarrayms/xarray_ms.py#L753-L755) for instance.

Let me see I can do this quickly now.

**Comment by sjperkins** [comment]
@o-smirnov when you say TAQL do you only mean the where clause or are you thinking of some greater incantations?

**Comment by o-smirnov** [comment]
Only the where. So you only really need the query() method.

**Comment by sjperkins** [comment]
Implemented in #25
