### ISSUE TITLE
UVW variable dimensions

### ISSUE THREAD

**Issue by Mulan-94** [ska-sa/xarray-ms#20]
Hi @sjperkins, Is it possible to have the dimension '(u,v,w)'  in the UVW variable dataArray as a name without the brackets? As it is I find it difficult to access it using the dot notation and selecting from it using the .sel functions. Or maybe there's something I missed?

**Comment by sjperkins** [comment]
@Mulan-94 Can you [attach an example](https://help.github.com/articles/creating-and-highlighting-code-blocks/) of how you're using the UVW dataarray? I haven't used xarray's selection criteria extensively in a while

**Comment by Mulan-94** [comment]
Yeah within the UVW data array, I want to access the data via the dimensions e.g `ds.UVW.row` but since UVW has the dimensions `'row'` and `'(u,v,w)'` then I can't access the 2nd dimension. e.g 
`ds.UVW.isel((u,v,w)=0)`

**Comment by sjperkins** [comment]
> Yeah within the UVW data array, I want to access the data via the dimensions e.g ds.UVW.row but since UVW has the dimensions 'row' and '(u,v,w)' then I can't access the 2nd dimension. e.g
ds.UVW.isel((u,v,w)=0)

OK I see this is not ideal. Is it possible to work around it for the moment with the following?

```python
ds.UVW.isel(**{'(u,v,w)':0})
```
```

**Comment by Mulan-94** [comment]
Ok yes, thanks!

**Comment by sjperkins** [comment]
Closed by #23
