### ISSUE TITLE
Pass key word Arguments to pyrap.tables.table

### ISSUE THREAD

**Issue by Mulan-94** [ska-sa/xarray-ms#21]
Hi @sjperkins , I would like to prevent `pyrap` from giving acknowledgement messages using the `ack` parameter but I notice when I pass this, it has no effect. Is it useful to add to the `xds_from_ms` api?
If I do have a patch already available that sort of works. Can I push it?

**Comment by sjperkins** [comment]
Hi @Mulan-94. It certainly would be useful -- I know @bennahugo wants it.

Push your changes up and I'll take a look.

**Comment by sjperkins** [comment]
Do create a pull request and please don't push to master.

**Comment by Mulan-94** [comment]
Ok great! But I don't have permission to push :( , could you assist?

**Comment by sjperkins** [comment]
You don't need write access to the repo, you can create a fork as create a pull request from that https://guides.github.com/activities/forking/

**Comment by sjperkins** [comment]
Implemented in #24
