### ISSUE TITLE
Intermittent User Table Locking Issues

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/xarray-ms#26]
@o-smirnov Ran into UserLocking issues when writing data

> More disappointingly, at the end it bombed out with:

```traceback
[######################################  ] | 95% Completed |  1hr 57min 58.2s
Traceback (most recent call last):
  File "/home/oms/projects/crystalball/bin/crystallball", line 7, in <module>
    pkg.main([a for a in sys.argv[1:]])
  File "/home/oms/projects/crystalball/Crystalball/main.py", line 10, in main
    predictor.predict( p.parse_args() )
  File "/home/oms/projects/crystalball/Crystalball/crystalball.py", line 373, in predict
    dask.compute(writes)
  File "/home/oms/.venv/cc/local/lib/python2.7/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/oms/.venv/cc/local/lib/python2.7/site-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/home/oms/.venv/cc/local/lib/python2.7/site-packages/dask/local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "/home/oms/.venv/cc/local/lib/python2.7/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/home/oms/.venv/cc/local/lib/python2.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/oms/.venv/cc/local/lib/python2.7/site-packages/xarrayms/xarray_ms.py", line 246, in _chunk_putcols_np
    startrow=rs, nrow=rl)
  File "/home/oms/.venv/cc/local/lib/python2.7/site-packages/xarrayms/table_proxy.py", line 74, in __call__
    return getattr(table, fn)(*args, **kwargs)
  File "/home/oms/.venv/cc/lib/python2.7/site-packages/python_casacore-3.0.0-py2.7-linux-x86_64.egg/casacore/tables/table.py", line 1157, in putcol
    self._putcol(columnname, startrow, nrow, rowincr, value)
RuntimeError: ColumnSet::doLock: table /data/oms/30Dor/cal/Tarantula_HI_8s4ch.ms should be locked when using UserLocking
```

And I ran into similar running a **single** test case, but the entire test suite runs fine: 

```traceback
$ py.test -s -v xarrayms/tests/ -k test_taql_where
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.16, pytest-4.4.1, py-1.8.0, pluggy-0.9.0 -- /home/sperkins/venv/xms/bin/python
cachedir: .pytest_cache
rootdir: /home/sperkins/work/ska/code/xarray-ms, inifile: setup.cfg
collected 38 items / 37 deselected / 1 selected                                                                                                                                                            

xarrayms/tests/test_ms.py::test_taql_where[index_cols0] FAILED

================================================================================================= FAILURES =================================================================================================
_______________________________________________________________________________________ test_taql_where[index_cols0] _______________________________________________________________________________________

ms = '/tmp/pytest-of-sperkins/pytest-121/msdir/test.ms', index_cols = ['TIME', 'ANTENNA1', 'ANTENNA2']

    @pytest.mark.parametrize('index_cols', [
        ["TIME", "ANTENNA1", "ANTENNA2"]])
    def test_taql_where(ms, index_cols):
        xds = list(xds_from_table(ms, taql_where="FIELD_ID >= 0 AND FIELD_ID < 2",
                                  columns=["FIELD_ID"],
                                  table_kwargs={'ack': False}))
    
        assert len(xds) == 1
        assert (xds[0].FIELD_ID.data.compute() == [0, 0, 0, 1, 1, 1, 1]).all()
    
        xds = list(xds_from_table(ms, taql_where="FIELD_ID >= 0 AND FIELD_ID < 2",
                                  group_cols=["DATA_DESC_ID", "SCAN_NUMBER"],
                                  columns=["FIELD_ID"],
>                                 table_kwargs={'ack': False}))

xarrayms/tests/test_ms.py:315: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
xarrayms/xarray_ms.py:821: in xds_from_table
    with pt.taql(query) as gq:
../../../../venv/xms/local/lib/python2.7/site-packages/casacore/tables/table.py:156: in taql
    tab = table(cmd, tabs, _oper=2)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <casacore.tables.table.table object at 0x7f604d92e3c0>
tablename = 'using style Python SELECT DATA_DESC_ID, SCAN_NUMBER, GROWID() as __tablerow__ FROM $1 GROUPBY DATA_DESC_ID, SCAN_NUMBER HAVING FIELD_ID >= 0 AND FIELD_ID < 2'
tabledesc = [<casacore.tables.table.table object at 0x7f604d92e310>], nrow = 0, readonly = True, lockoptions = 'default', ack = True, dminfo = {}, endian = 'aipsrc', memorytable = False
concatsubtables = [], _columnnames = [], _datatypes = [], _oper = 2, _delete = False

    def __init__(self, tablename, tabledesc=False, nrow=0, readonly=True,
                 lockoptions='default', ack=True, dminfo={}, endian='aipsrc',
                 memorytable=False, concatsubtables=[],
                 _columnnames=[], _datatypes=[],
                 _oper=0, _delete=False):
        """Open or create a table."""
        if _oper == 1:
            # This is the readascii constructor.
            tabname = _remove_prefix(tablename)
            Table.__init__(self, tabname, tabledesc, nrow, readonly,
                           lockoptions, ack, dminfo, endian, memorytable,
                           _columnnames, _datatypes)
        elif _oper == 2:
            # This is the query or calc constructor.
>           Table.__init__(self, tablename, tabledesc)
E           RuntimeError: Error in TaQL command: 'using style Python SELECT DATA_DESC_ID, SCAN_NUMBER, GROWID() as __tablerow__ FROM $1 GROUPBY DATA_DESC_ID, SCAN_NUMBER HAVING FIELD_ID >= 0 AND FIELD_ID < 2'
E             ColumnSet::doLock: table /tmp/pytest-of-sperkins/pytest-121/msdir/test.ms should be locked when using UserLocking

../../../../venv/xms/local/lib/python2.7/site-packages/casacore/tables/table.py:331: RuntimeError
================================================================================= 1 failed, 37 deselected in 0.30 seconds ==================================================================================
```

**Comment by sjperkins** [comment]
Possibly fixed in https://github.com/ska-sa/xarray-ms/pull/25/commits/cccb9f39efa712b96be1dc346ada65e57f8c62c0

**Comment by sjperkins** [comment]
I fixed my issue by explicitly opening the table for inspection with `lockoptions='user'` and locking the table directly after open.

There seemed to be some unholy interaction between opening the table in standard 'auto' mode and running a TAQL query. I would guess py.test's caching mechanism kept an old table object around opened in 'user' mode somewhere.

```python
with pt.table(ms, lockoptions='user') as T:
  T.lock()
  ...
  with pt.taql("SELECT * FROM $T ...") as Q:
     Q.getcol("BLAH")
  ...
  T.unlock()
```

**Comment by o-smirnov** [comment]
Yeah, I had similar issues in radiopadre, ended up going to ``lockoptions='user'`` throughout. Something's just not (always) kosher with the auto behaviour...

Beware though, lock/unlock doesn't nest. You might want to borrow my context manager from here: https://github.com/ratt-ru/radiopadre-devel/blob/master/radiopadre/casatable.py#L105

**Comment by sjperkins** [comment]
> Beware though, lock/unlock doesn't nest. You might want to borrow my context manager from here: https://github.com/ratt-ru/radiopadre-devel/blob/master/radiopadre/casatable.py#L105

Thanks for the link. It looks to me like you're implementing a re-entrant lock? I'm guessing it's not threadsafe because radiopadre is the standard single-process, single-thread Python application model?

In a standard threading paradigm I would expect multiple threads to be able to call the lock/unlock method on the same table object without deadlocking. By contrast, I would expect a single Python thread to deadlock trying to lock the same table object twice (without an unlock between lock acquisitions).

Then again, I don't know how casacore implements it's mutexes and locks under the hood so there may be gremlins I'm unaware of.

**Comment by o-smirnov** [comment]
> I'm guessing it's not threadsafe because radiopadre is the standard single-process, single-thread Python application model?

Correct. I don't know how casacore plays with threads or whether it even does. Radiopadre is single-threaded. What it tries to do is to hang onto locks for the shortest time possible (because its use case is to "spy" on MSs that another application may be using in anger), so auto-locking did not suit the purpose.

> By contrast, I would expect a single Python thread to deadlock trying to lock the same table object twice (without an unlock between lock acquisitions).

And I can assure you that casacore *will* violate those expectations. Once you have acquired a lock, you may keep calling lock() with no deadlock. On the other hand, unlock() will always drop the lock immediately (i.e. there's no internal counter of how many times lock has been called). This makes nested locks a pain, and was the reason I wrote the contextmanager linked to above.

**Comment by sjperkins** [comment]
One other construct that might contribute to this problem is the [TableCache](https://github.com/ska-sa/xarray-ms/blob/6e6858b784456deeb1edb3a6945e235d72907b18/xarrayms/table_cache.py#L52-L58), which opens tables and does not close them [until the application exits](https://github.com/ska-sa/xarray-ms/blob/6e6858b784456deeb1edb3a6945e235d72907b18/xarrayms/table_cache.py#L66).

**Comment by sjperkins** [comment]
> And I can assure you that casacore will violate those expectations. Once you have acquired a lock, 

Yeah, I consider my expectations subverted.

> you may keep calling lock() with no deadlock. On the other hand, unlock() will always drop the lock immediately (i.e. there's no internal counter of how many times lock has been called). This makes nested locks a pain, and was the reason I wrote the contextmanager linked to above.

As it stands, I don't think xarray-ms is attempting a double-locking/unlocking paradigm *within* a single thread. Maybe I should drop Ger an email to ask whether multiple threads locking/unlocking the table object might cause a problem.

**Comment by sjperkins** [comment]
Closed by #27.

**Comment by sjperkins** [comment]
This revealed itself again in 0.1.4 when used in tricolour: https://github.com/ska-sa/tricolour/issues/24

**Comment by sjperkins** [comment]
From correspondence with @gervandiepen:

> A single table should be accessed from one thread only; the Table object is not thread-safe. Internally it uses some caching which cannot be shared amongst threads.
However, it is safe to access different tables in different threads.

> Reading one table from multiple processes is always safe and does not require locking. But when writing, there can only be a single writer or multiple readers (not both as writing needs an exclusive lock).

**Comment by sjperkins** [comment]
Closed by #31

**Comment by sjperkins** [comment]
Ran into this again over here: https://github.com/ska-sa/xarray-ms/pull/41/commits/356ac1964d51685225fe7f958bb253f58744cdd3#diff-8d6172391a4dbcad10fb5824df934dfeR114 and found some workaround. Added a description of the issue.

 @SpheMakh I hope to support two table objects referencing the same MS, one readonly, one writeonly. But these locking issues seem to crop up. Hopefully it will be "OK". I think the current implementation should be more robust, but we'll have to see how it goes.

**Comment by o-smirnov** [comment]
You might be amused by this little detail @sjperkins: some CASA tasks don't even bother with doing locking right.

I have a Python process holding a table open with ``lockoptions='user'``, and no lock on the table. And consequently I have a CASA task bombing out with:

```
2019-12-04 07:31:05	SEVERE	Calibrater::solve	Caught exception: Specified caltable (../OldDevils/output-ep1-1/caltables/od1r-1557766852_F126_CGCG044_4corr-1gc1_bpcal.K0) exists and
2019-12-04 07:31:05	SEVERE	Calibrater::solve+	 cannot be replaced (or appended to) because it appears to be open somewhere (Quit plotcal?).
```

Because yes, we're just going to ignore all the thoughtful locking functionality that @gervandiepen developed, and either bulldoze the whole thing, or bomb out because we want the table all to ourselves ("my precioussss!") Because we're CASA and we can!

Anyway no action to be taken, just needed a place to rant...

**Comment by sjperkins** [comment]
I came across [BlazingSQL](https://docs.blazingdb.com/docs) yesterday. GPU-Accelerated, dask-enabled SQL DB... For the future perhaps.

**Comment by bennahugo** [comment]
KEEP CALM

AND

DITCH CASA
