### ISSUE TITLE
Mitigate pathological row orderings

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/xarray-ms#8]
Certain TAQL groupings and ordering can result in pathological orderings, from a disk access perspective. For e.g. `ORDERBY ANTENNA2` will frequently generate singleton rows which are highly inefficient for disk read/writes.

One possible strategy for mitigating this within xarray-ms would be too resort all rows within a dask chunk in an attempt to generate more consecutive row runs and better disk access patterns.

Then, once the chunk data is loaded, it can be resorted to the requested ordering

**Comment by o-smirnov** [comment]
Not sure this is an issue really. If the user wants to run a pathologically-sorted MS, why worry about taking their rope away? As long as it is clearly documented what a decent, God-fearing ordering is, can't we leave it up to the user to resort if necessary?

**Comment by sjperkins** [comment]
@o-smirnov Yes, I'm not really intending to implement this.

I should've labelled this as `nice-to-have` and `possible-ways-to-solve-this` in case we do run into it later on.

**Comment by sjperkins** [comment]
Closed by #12
